### ISSUE TITLE
On telegram, we always get video not found UI

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#283]
reproduce by opening (say) a post in telegram and try to placy the vid

![0e920ab5-66c4-4d07-92a7-742d53565f2d](https://user-images.githubusercontent.com/7697924/38733357-9687a88a-3eef-11e8-877b-78c06da07940.png)

**Comment by bent0b0x** [comment]
FYI I just tested on staging, and I think #437 may have resolved the original issue. However, we are not always getting the "Ooooops, video not found!" message on telegram

**Comment by bent0b0x** [comment]
I would love some ideas as to how to debug this, as I really have no idea 😄

**Comment by bent0b0x** [comment]
I believe this is related to our opengraph implementation. I do not think it is working, as can be seen by testing on https://developers.facebook.com/tools/debug/sharing/

**Comment by felipegaucho** [comment]
I believe this is solved:

<img width="1003" alt="screen shot 2018-04-13 at 3 42 55 am" src="https://user-images.githubusercontent.com/26517120/38720498-d6bedd42-3ecc-11e8-8097-90d84d2c5ca1.png">

<img width="1035" alt="screen shot 2018-04-13 at 3 43 03 am" src="https://user-images.githubusercontent.com/26517120/38720503-d8909db8-3ecc-11e8-8542-6548deaab781.png">

Lacking maybe only the play/initial state :) https://github.com/Paratii-Video/paratii-portal/issues/449

**Comment by bent0b0x** [comment]
Telegram still does not work. I’m going to reopen and change the title

**Comment by geckoslair** [comment]
@bent0b0x please let me know if i can help you =)

**Comment by bent0b0x** [comment]
I think I know the fix for this, might have to push it to staging to test but working on it

**Comment by bent0b0x** [comment]
Okay, this is resolved on production (with no action). The reason it looked broken is because staging and local does not work.

[These lines](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/server/routes/index.js#L55-L66) are the reason. I don't know if this is a big deal; essentially we have hard-coded `portal.paratii-video` in some places, which will make staging embeds not work. This is not great for testing. I have opened up [this issue](https://github.com/Paratii-Video/paratii-portal/issues/475) so that we can revisit.
